retry_if_fail on extension downloads

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -203,12 +203,27 @@ jobs:
           /home/runner/civicrm-cv/cv ev '\Civi::settings()->set("ext_repo_url", "https://civicrm.org/extdir/ver={ver}|cms={uf}|ready=");'
           /home/runner/civicrm-cv/cv ev '\Civi::settings()->set("http_timeout", 60);'
           # Apparently we have to install it, otherwise stripe gives a dependency error even with install=0. I think that's a bug, but let's just do it. This is a fake install anyway.
-          /home/runner/civicrm-cv/cv api3 Extension.download install=1 key=mjwshared
-          /home/runner/civicrm-cv/cv api3 Extension.download install=1 key=firewall
-          /home/runner/civicrm-cv/cv api3 Extension.download install=1 key=mjwpaymentapi
-          /home/runner/civicrm-cv/cv api3 Extension.download install=1 key=com.drastikbydesign.stripe
-          /home/runner/civicrm-cv/cv api3 Extension.download install=0 key=com.iatspayments.civicrm
-          /home/runner/civicrm-cv/cv api3 Extension.download install=0 key=com.aghstrategies.uscounties
+
+          # We frequently get "The CiviCRM public extensions directory at https://civicrm.org/extdir/ver=5.69.5|cms=Drupal8|ready= could not be contacted",
+          # So we'll retry try eachh extension download several times before giving up
+          function retry_if_fail ()
+            local command="${@}"
+            for ((n=3; n>0; n--)); do
+              $command
+              if [[ $? == 0 ]]; then
+                break
+              fi
+              sleep 30
+            done
+            [[ $n == 0 ]] && echo "Failed to download extenion!" && exit 1
+          }
+          
+          retry_if_fail /home/runner/civicrm-cv/cv api3 Extension.download install=1 key=mjwshared
+          retry_if_fail /home/runner/civicrm-cv/cv api3 Extension.download install=1 key=firewall
+          retry_if_fail /home/runner/civicrm-cv/cv api3 Extension.download install=1 key=mjwpaymentapi
+          retry_if_fail /home/runner/civicrm-cv/cv api3 Extension.download install=1 key=com.drastikbydesign.stripe
+          retry_if_fail /home/runner/civicrm-cv/cv api3 Extension.download install=0 key=com.iatspayments.civicrm
+          retry_if_fail /home/runner/civicrm-cv/cv api3 Extension.download install=0 key=com.aghstrategies.uscounties
           # temporary iats patches for undeclared vars
           cd com.iatspayments.civicrm
           curl -L -O https://patch-diff.githubusercontent.com/raw/iATSPayments/com.iatspayments.civicrm/pull/455.diff
