Apache with logs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -64,6 +64,8 @@ jobs:
           touch test1
           ls -al .
           env
+          uname -a
+          df -h
       - name: Create MySQL Docker container with data in RAM
         run: |
           /usr/bin/docker create --name mysql_${{ strategy.job-index }} -p 3306 --network host --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --tmpfs /var/lib/mysql -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" -e "MYSQL_DATABASE=db" -e GITHUB_ACTIONS=true -e CI=true mysql:8.0 --skip-log-bin
@@ -73,18 +75,18 @@ jobs:
       - uses: actions/checkout@v4
       - uses: shivammathur/setup-php@v2
         with:
-            php-version: ${{ matrix.php }}
-            extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, libapache2-mod-php
-            coverage: none
-            tools: composer:v2
+          php-version: ${{ matrix.php }}
+          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, libapache2-mod-php
+          coverage: none
+          tools: composer:v2
       - name: Get composer cache directory
         id: composercache
         run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
       - uses: actions/cache@v4
         with:
-            path: ${{ steps.composercache.outputs.dir }}
-            key: ${{ runner.os }}-${{ matrix.drupal }}-composer-${{ hashFiles('**/composer.json') }}
-            restore-keys: ${{ runner.os }}-composer-
+          path: ${{ steps.composercache.outputs.dir }}
+          key: ${{ runner.os }}-${{ matrix.drupal }}-composer-${{ hashFiles('**/composer.json') }}
+          restore-keys: ${{ runner.os }}-composer-
       - name: Setup problem matchers for PHPUnit
         run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
       # Notes
@@ -136,12 +138,10 @@ jobs:
       - name: Setup Ping Diagnostics
         run: |
           mkdir -p /home/runner/drupal/web/sites/simpletest/browser_output/
-          ping github.com > /home/runner/drupal/web/sites/simpletest/browser_output/ping_github.log &
+          #ping github.com > /home/runner/drupal/web/sites/simpletest/browser_output/ping_github.log &
           ping localhost > /home/runner/drupal/web/sites/simpletest/browser_output/ping_localhost.log &
-          ping google.com > /home/runner/drupal/web/sites/simpletest/browser_output/ping_google.log &
+          #ping google.com > /home/runner/drupal/web/sites/simpletest/browser_output/ping_google.log &
           /usr/bin/docker ps -a
-          uname -a
-          df -h
       - name: Suppress links to screenshots
         # There's so many! They can be useful locally if running one test, but they aren't useful here and cause massive scrolling.
         run: |
@@ -256,12 +256,12 @@ jobs:
       - name: Run chromedriver
         run: |
           #chromedriver --port=9515 --verbose &> /home/runner/drupal/web/sites/simpletest/browser_output/chromedriver.log &
-          export DISPLAY=:99
+          #export DISPLAY=:99
           #sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
-          sudo Xvfb -ac :99 -screen 0 1920x2048x24 > /dev/null 2>&1 &
+          #sudo Xvfb -ac :99 -screen 0 1920x2048x24 > /dev/null 2>&1 &
           chromedriver --port=4444 --verbose &> /home/runner/drupal/web/sites/simpletest/browser_output/chromedriver.log &
-      - name: Run php built-in server
-        run: PHP_CLI_SERVER_WORKERS=32 php -S 127.0.0.1:8080 -t ~/drupal/web &
+      # - name: Run php built-in server
+      #   run: PHP_CLI_SERVER_WORKERS=32 php -S 127.0.0.1:8080 -t ~/drupal/web &
       # - name: Patch Webdriver curl
       #   if: ${{ matrix.drupal != '10.3.*' }}
       #   run: |
@@ -278,46 +278,46 @@ jobs:
       #                      WebDriverException::NO_PARAMETERS_EXPECTED,
       #     EOF
       #     patch ~/drupal/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php /tmp/patch1 
-      # - name: Install Apache web server
-      #   run: |
-      #     sudo apt update
-      #     sudo apt install apache2
-      #     cat << 'EOF' > /tmp/simpletest.conf
-      #       Listen 8080
-      #       <VirtualHost *:8080>
-      #         ServerAdmin webmaster@localhost
-      #         ServerName 127.0.0.1
-      #         #ServerAlias www.your_domain
-      #         DocumentRoot /home/runner/drupal/web
-      #         <Directory "/home/runner/drupal/web">
-      #           Options All
-      #           AllowOverride All
-      #           <IfModule mod_authz_host.c>
-      #               Require all granted
-      #           </IfModule>
-      #         </Directory>
-      #         ErrorLog ${APACHE_LOG_DIR}/error.log
-      #         CustomLog ${APACHE_LOG_DIR}/access.log combined
-      #       </VirtualHost>
-      #     EOF
-      #     sudo mv /tmp/simpletest.conf /etc/apache2/sites-available/simpletest.conf
-      #     sudo bash -c 'echo -e \\nexport APACHE_RUN_USER=runner\\nexport APACHE_RUN_GROUP=runner\\n >> /etc/apache2/envvars'
-      #     #sudo chown -R www-data:www-data /home/runner/drupal
-      #     #sudo chmod -R 777 /home/runner/drupal
-      #     sudo apt-get install libapache2-mod-php${{ matrix.php }}
-      #     sudo a2ensite simpletest.conf
-      #     sudo a2dissite 000-default.conf
-      #     sudo a2dismod "php*"
-      #     sudo a2enmod php${{ matrix.php }}
-      #     sudo apache2ctl configtest #check for config errors
-      #     sudo systemctl restart apache2
-      #     sudo systemctl status apache2
-      #     ps alx | grep apache
-      #     cd /tmp
-      #     wget http://127.0.0.1:8080 -O index1.php || echo 'wget http://127.0.0.1:8080 failed'
-      #     cat index1.php
-      #     cat /var/log/apache2/error.log
-      #     cat /var/log/apache2/access.log
+      - name: Install Apache web server
+        run: |
+          sudo apt update
+          sudo apt install apache2
+          cat << 'EOF' > /tmp/simpletest.conf
+            Listen 8080
+            <VirtualHost *:8080>
+              ServerAdmin webmaster@localhost
+              ServerName 127.0.0.1
+              #ServerAlias www.your_domain
+              DocumentRoot /home/runner/drupal/web
+              <Directory "/home/runner/drupal/web">
+                Options All
+                AllowOverride All
+                <IfModule mod_authz_host.c>
+                    Require all granted
+                </IfModule>
+              </Directory>
+              ErrorLog ${APACHE_LOG_DIR}/error.log
+              CustomLog ${APACHE_LOG_DIR}/access.log combined
+            </VirtualHost>
+          EOF
+          sudo mv /tmp/simpletest.conf /etc/apache2/sites-available/simpletest.conf
+          sudo bash -c 'echo -e \\nexport APACHE_RUN_USER=runner\\nexport APACHE_RUN_GROUP=runner\\n >> /etc/apache2/envvars'
+          #sudo chown -R www-data:www-data /home/runner/drupal
+          #sudo chmod -R 777 /home/runner/drupal
+          sudo apt-get install libapache2-mod-php${{ matrix.php }}
+          sudo a2ensite simpletest.conf
+          sudo a2dissite 000-default.conf
+          sudo a2dismod "php*"
+          sudo a2enmod php${{ matrix.php }}
+          sudo apache2ctl configtest #check for config errors
+          sudo systemctl restart apache2
+          sudo systemctl status apache2
+          ps alx | grep apache
+          cd /tmp
+          wget http://127.0.0.1:8080 -O index1.php || echo 'wget http://127.0.0.1:8080 failed'
+          cat index1.php
+          cat /var/log/apache2/error.log
+          cat /var/log/apache2/access.log
       # - name: Patch Mink loop delay
       #   run: sed -i -Ee 's/usleep\(10000\)/usleep(100000)/' ~/drupal/vendor/behat/mink/src/Element/Element.php
       - name: Run PHPUnit
@@ -357,4 +357,5 @@ jobs:
           name: screenshots.${{ env.UPLOADNAME }}
           # For some reason Drupal prints here and not our specified BROWSERTEST_OUTPUT_DIRECTORY.
           path: '/home/runner/drupal/web/sites/simpletest/browser_output'
+          path: /var/log/apache2/
           retention-days: 7
